### ISSUE TITLE
@types/express should be moved under devDependencies

### ISSUE THREAD

**Issue by attila123** [LionC/express-basic-auth#4]
Hi,
I think `@types/express` should be moved under devDependencies in package.json, because it is not necessary to run the module in production, rather it s needed only during development.
Due to this issue, some `@types/...` modules remain installed even after `npm prune --production` (which is supposed to remove the devDependencies), which is not so nice.
What do you think?

**Comment by LionC** [comment]
Hi attila,

thanks for your input! That sounds like it makes sense - do you want to open a Pull Request or should I just do it?

**Comment by attila123** [comment]
Hi LionC,
I'd appreciate if you did this, thanks.

**Comment by toverux** [comment]
Yep, putting it in the deps is not the best idea I've had.
I did it because, if the consumer does not install it manually, it will get an error about "express not being a module". But I think now that it is "expected", and can avoid other dependency problems. Moreover, someone who uses express-basic-auth should already have @types/express in its own deps.
Also, peerDeps would have been a good choice if it would not force JS users to install it too.

**Comment by attila123** [comment]
Hi @toverux , I am not sure I understand correctly what you wrote. Do you mean that if @types/express is not installed in production then it will result in an "express not being a module" error? I though that @types/express is just some kind of type hint for typescript, and therefore it is only needed for developers, and it is not needed in production (for the transpiled code).
Or do you mean the use case when typescript files are directly used in production? (I think I read something that it is possible somehow, but our project does the transpiling in build time to ES6, so we don't use .ts files in production.)
Unfortunately I am not familiar with peerDeps.

**Comment by toverux** [comment]
No, I don't refer to production ;) 
If you don't have @types/express in your own project (in development) and that express-basic-auth removes it, TypeScript won't understand those express references. And emit an error like _"Could not find a declaration file for module 'express'"_.

I'll do some tests concerning that asap and create the PR myself. Thanks for reporting the issue - since anyway, having @types/express in `dependencies` is definitely not a good approach.

**Comment by LionC** [comment]
Thanks for taking care of the PR Morgan!

________________________________

**Comment by fklingler** [comment]
This issue should be closed I think :) :+1:

**Comment by attila123** [comment]
Sorry, somehow did not notice that it got solved.
Verified with 1.1.3, got fixed, so closing this issue.
Thank you very much for fixing this! :)

**Comment by vjpr** [comment]
@LionC 

This issue is wrong.

`express-basic-auth.d.ts` imports `express`, and is present when published. TypeScript will therefore search for `express/node_modules/@types/express.d.ts` when this package is used by something else.

This is breaking my build.

**Comment by vjpr** [comment]
https://github.com/LionC/express-basic-auth/pull/5#issuecomment-459910146
